services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: weather-backend
    environment:
      DB_PATH: "/var/lib/weather/data.db"
      MQTT_HOST: "${MQTT_HOST:-10.0.0.30}"
      MQTT_PORT: "${MQTT_PORT:-1883}"
      MQTT_USER: "${MQTT_USER:-AnimeArchive}"
      MQTT_PASSWORD: "${MQTT_PASSWORD:-AnimeArchive}"
      MQTT_TOPIC: "${MQTT_TOPIC:-weather_station/bme680}"
      FLASK_ENV: "production"
    ports:
      - "5000:5000"

    volumes:
      - weather_db:/var/lib/weather

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:5000/latest || exit 1"]
      interval: 20s
      timeout: 3s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: weather-frontend
    # Frontend needs the public URL the browser can reach:
    environment:
      API_BASE_URL: "${API_BASE_URL:-http://localhost:5000}"
      LOG_LEVEL: "${FRONTEND_LOG_LEVEL:-debug}"
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy

volumes:
  weather_db: